name: viserpay
description: A new Flutter project.

publish_to: 'none'
version: 1.1.1+4

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.0.1
  flutter_inappwebview: ^5.8.0
  flutter_local_notifications: ^17.2.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.4
  flutter_widget_from_html: ^0.15.1
  get: ^4.6.6
  http: ^1.1.2
  im_stepper: ^1.0.1+1
  image_picker: ^1.0.4
  intl: ^0.19.0
  local_auth: ^2.1.7
  lottie: ^3.1.2
  octo_image: ^2.0.0
  open_file: ^3.3.2
  path_provider: ^2.0.9
  permission_handler: ^11.1.0
  pdf: ^3.10.2
  pin_code_fields: ^8.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  share_plus: ^10.0.0
  shared_preferences: ^2.0.13
  shimmer: ^3.0.0
  url_launcher: ^6.2.2
  vibration: ^1.8.4
  flutter_exit_app: ^1.1.2
  another_flushbar: ^1.12.30
  animated_text_kit: ^4.2.2
  awesome_dialog: ^3.1.0
  cached_network_image: ^3.3.0
  carousel_slider: ^5.0.0
  circular_countdown_timer: ^0.2.3
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  dots_indicator: ^3.0.0
  dotted_border: ^2.0.0+2
  expandable_page_view: ^1.0.17
  fast_contacts: ^3.1.4
  file_manager: ^1.0.2
  file_picker: ^7.0.2
  firebase_core: ^3.1.1
  firebase_core_platform_interface: ^5.0.0
  firebase_messaging: ^15.0.2
  flutter_animate: ^4.5.0
  zoom_tap_animation: ^1.1.0
  fluttertoast: ^8.2.8
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  restart_app: ^1.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/icon/
    - assets/img/
    - assets/animation/

  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Bold.ttf
        - asset: assets/fonts/Rajdhani-Light.ttf
        - asset: assets/fonts/Rajdhani-Medium.ttf
        - asset: assets/fonts/Rajdhani-Regular.ttf
        - asset: assets/fonts/Rajdhani-SemiBold.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
